<html>
        <head>
                <meta http-equiv="content-type" content="text/html; charset=UTF-8">
                <title>Boostrap Validator</title>
                <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.js"></script>  
                <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
                <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>  
                <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/css/bootstrapValidator.min.css"/>
                <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/js/bootstrapValidator.min.js"> </script>
                <script>
                $(document).ready(function() {
    $('#f1').bootstrapValidator({
        container: '#messages',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            firstname: {
                validators: {
                    notEmpty: {
                        message: 'The first name is required and cannot be empty'
                    }
                }
            },

            lastname: {
                validators: {
                    notEmpty: {
                        message: 'The last name is required and cannot be empty'
                    }
                }
            },
            email: {
                validators: {
                    notEmpty: {
                        message: 'The email address is required and cannot be empty'
                    },
                    emailAddress: {
                        message: 'The email address is not valid'
                    }
                }
            },
            phone: {
                validators: {
                    notEmpty: {
                        message: 'The mobile number is required and cannot be empty'
                    },
                    stringLength: {
                        max: 10,
                        message: 'The mobile number must be 10 characters long'
                    }
                }
            },
            comment: {
                validators: {
                    notEmpty: {
                        message: 'The comment is required and cannot be empty'
                    },
                    stringLength: {
                        max: 500,
                        message: 'The comment must be less than 500 characters long'
                    }
                }
            }
        }
    });
});
</script>
        </head>
   <body>

        <form id="f1" method="post" class="form-horizontal" action="<?php echo $block->getBaseUrl().'feedback/index/save' ?>">
                <div class="form-group">
                    <label class="col-md-3 control-label">First Name</label>
                    <div class="col-md-6">
                        <input class="form-control" type="text" id="firstname" name="firstname" placeholder="Your name.." >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Last Name</label>
                    <div class="col-md-6">
                        <input class="form-control" type="text" id="lastname" name="lastname" placeholder="Your last name.." >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Email</label>
                    <div class="col-md-6">
                        <input class="form-control" type="text" id="email" name="email" placeholder="Your email.." >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Mobile No.</label>
                    <div class="col-md-6">
                        <input class="form-control" type="text" id="phone" name="phone" placeholder="Your phone no..." >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Comment</label>
                    <div class="col-md-6">
                        <textarea class="form-control" id="comment" name="comment" placeholder="Write something.." style="height:100px" ></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <div id="messages"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </div>
        </form>    
    </body>
</html>